nginx:
  build: nginx-image
  links:
    - letsencrypt
    - app
  environment:
    - MY_DOMAIN_NAME=app.carstay.jp
  mem_limit: 1g
  cpu_shares: 256
  # restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - letsencrypt
letsencrypt:
  build: certbot-image
  environment:
    - MY_DOMAIN_NAME=app.carstay.jp
  command: /init.sh
letsencryptRenew:
  build: certbot-image
  environment:
    - MY_DOMAIN_NAME=app.carstay.jp
  command: /renew.sh
