version: '3'
services:
    letsencrypt:
      build: certbot-image
      environment:
        - MY_DOMAIN_NAME=test.astroslay.com
      command: ["bash", "/init.sh"]
      volumes:
        - ./letscript/confg/:/etc/letsencrypt
        - ./letscript/lib:/var/lib/letscript
